require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end

desc "Start the server"
task :server do
  if ActiveRecord::Base.connection.migration_contents
    puts "Migrations are pending. Make sure to run 'bundle exec rake db:migrate"
    return
  end
  exec "rerun -b 'rackup config.ru'"
end